name: PR Test Trigger

on:
  issue_comment:
    types: [created]

jobs:
  run-tests:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/test' &&
      contains(fromJson('["OWNER", "COLLABORATOR"]'), github.event.comment.author_association)
    uses: ./.github/workflows/tests.yml
    secrets: inherit
